package com.kirana.model;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMarshaller;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMarshalling;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.wordnik.swagger.annotations.ApiModelProperty;
import java.beans.XMLDecoder;
import java.beans.XMLEncoder;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.Serializable;
import java.util.HashMap;








@DynamoDBTable(tableName="order")
public  class Order implements Serializable {
    
    
  
    @ApiModelProperty(hidden = true, required=false)    
    private String id;
    @ApiModelProperty(hidden = true, required=false)
    private long shopId;
    
    @ApiModelProperty(notes = "yyyy-MM-dd'T'HH:mm:ss.SSS'Z' --> 2001-07-04T12:08:56.235-0700")
    private String createdAt;
    
    @ApiModelProperty(notes = "yyyy-MM-dd'T'HH:mm:ss.SSS'Z' --> 2001-07-04T12:08:56.235-0700")
    private String updatedAt;
    
    
    @ApiModelProperty(notes = "Hash of productid and quantity, ex: {'idly':1,'porotta':2}")
    private HashMap<String,Integer> orderList;
    
    @ApiModelProperty(notes = "Extra info like geo location....")
    private HashMap<String,String> extraInfo;

    @JsonIgnore
    @ApiModelProperty(hidden = true, required=false)
    private boolean isOrderCreate;

    public boolean isIsOrderCreate() {
        return isOrderCreate;
    }

    public void setIsOrderCreate(boolean isOrderCreate) {
        this.isOrderCreate = isOrderCreate;
    }
    
    
    
    
    public Order(Long shopId) {
        this.isOrderCreate = true;
        this.shopId=shopId;
    }

    public Order() {
        this.isOrderCreate = true;
    }

    @DynamoDBMarshalling(marshallerClass = OrderListConverter.class) 
    public HashMap<String, Integer> getOrderList() {return orderList; }
    public void setOrderList(HashMap<String, Integer> orderList) {this.orderList = orderList; }

    
    @DynamoDBMarshalling(marshallerClass = ExtraInfoConverter.class) 
    public HashMap<String, String> getExtraInfo() {return extraInfo;}
    public void setExtraInfo(HashMap<String, String> extraInfo) {this.extraInfo = extraInfo; }
    
    @DynamoDBIndexRangeKey(attributeName="created_at",globalSecondaryIndexName = "shop_id-created_at-index")
    public String getCreatedAt() { return createdAt; }
    public void setCreatedAt(String createdAt) { this.createdAt = createdAt; }
    
    
    @DynamoDBIndexHashKey(attributeName="shop_id",globalSecondaryIndexName = "shop_id-created_at-index")
    public Long getShopId() { return shopId; }
    public void setShopId(Long shopId) {this.shopId = shopId; }

    @DynamoDBAttribute(attributeName = "updated_at")
    public String getUpdatedAt() {return updatedAt; }
    public void setUpdatedAt(String updatedAt) {this.updatedAt = updatedAt; }
    
    @DynamoDBAutoGeneratedKey
    @DynamoDBHashKey(attributeName = "id")
    public String getId() {return id; }
    public void setId(String id) {this.id=id; }
   
    
     
    @Override
    public String toString() {
        return "Order{" + "shopId=" + shopId + ", createdAt=" + createdAt + ", updatedAt=" + updatedAt + '}';
    }
    
    
    
    static public class OrderListConverter implements DynamoDBMarshaller<HashMap<String,Integer>> {
        @Override
        public String marshall(HashMap<String,Integer> getterReturnResult) {
            ByteArrayOutputStream bos = new ByteArrayOutputStream();
            XMLEncoder xmlEncoder = new XMLEncoder(bos);
            xmlEncoder.writeObject(getterReturnResult);
            xmlEncoder.flush();
             return bos.toString();
        }
        @Override
        public HashMap<String,Integer> unmarshall(Class<HashMap<String,Integer>> clazz, String obj) {
            XMLDecoder xmlDecoder = new XMLDecoder(new ByteArrayInputStream(obj.getBytes()));
            HashMap<String,Integer> list = (HashMap<String,Integer>) xmlDecoder.readObject();
            return list;
        }
    }
    
    static public class ExtraInfoConverter implements DynamoDBMarshaller<HashMap<String,String>> {
        @Override
        public String marshall(HashMap<String,String> getterReturnResult) {
            ByteArrayOutputStream bos = new ByteArrayOutputStream();
            XMLEncoder xmlEncoder = new XMLEncoder(bos);
            xmlEncoder.writeObject(getterReturnResult);
            xmlEncoder.flush();
             return bos.toString();
        }
        @Override
        public HashMap<String,String> unmarshall(Class<HashMap<String,String>> clazz, String obj) {
            XMLDecoder xmlDecoder = new XMLDecoder(new ByteArrayInputStream(obj.getBytes()));
            HashMap<String,String> list = (HashMap<String,String>) xmlDecoder.readObject();
            return list;
        }
    }
    

}
